### ISSUE TITLE
Issue with OutputFile Paths

### ISSUE THREAD

**Issue by NikCharlebois** [Microsoft/SharePointDSC.Reverse#16]
**Details of the scenario you try and problem that is occurring:**
The code handling the OutputFile path (to specify where to save the output) only looks for paths with '/' instead of '\'. We need to make sure both are handled.

**The DSC configuration that is using the resource:**
N/A

**Version of the Operating System and PowerShell the DSC Target Node is running:**
N/A

**Version of the DSC module you're using:**
1.8.0.0

**Comment by brianlala** [comment]
In what case would a (local or network) path have a forward slash though? Normally we'd only see this in URLs.

**Comment by NikCharlebois** [comment]
Agreed. I don't recall the entire reason for the logic (if there even is any), but I seem to recall, that I had to do such a path manipulation in some UNC cases:

ex: file://\\DSC-Share\Nik\test.ps1
