### ISSUE TITLE
Get Credentials Invalid variable name when "@" symbol is part of account name

### ISSUE THREAD

**Issue by llowevad** [Microsoft/SharePointDSC.Reverse#29]
**Details of the scenario you try and problem that is occurring:**
Installed 1.9.1 and ran it in my lab environment. Execution was successful, but when running the output file it received errors regarding invalid value in variable name. This is in reference to having a user account in a user@domain format. The "@" symbol is used as part of the variable name, which powershell doesn't like

**The DSC configuration that is using the resource:**
n/a

**Version of the Operating System and PowerShell the DSC Target Node is running:**
Windows Server 2012 / PowerShell 5.1

**Version of the DSC module you're using:**
1.9.1

![image](https://user-images.githubusercontent.com/8823690/31280829-a8bee210-aa7b-11e7-8e0a-50e0175baacc.png)

![image](https://user-images.githubusercontent.com/8823690/31280867-ca9ac228-aa7b-11e7-8349-7aea0896d606.png)

**Comment by NikCharlebois** [comment]
@llowevad if you do a search in your .ps1 config file, where is the $Credsadmin@demo.com variable used? In what DSC Resource. Thanks

**Comment by llowevad** [comment]
SPWebAppPolicy 29ae02f5-6a38-4ad5-b23e-2030bd30da86
        {
            PsDscRunAsCredential = $CredsAdmin;
            SetCacheAccountsPolicy = $False;
            WebAppUrl = "https://sharepoint.demo.com/";
            Members = MSFT_SPWebPolicyPermissions{
                Username =  $Credsadmin@demo_com.UserName
                IdentityType = "Claims"
                PermissionLevel = "Full Control"
                ActAsSystemAccount = $False
            };
        }
