### ISSUE TITLE
Variable naming doesn't handle spaces in the service's username

### ISSUE THREAD

**Issue by adamrushuk** [Microsoft/SharePointDSC.Reverse#30]
**Details of the scenario you try and problem that is occurring:**

Just testing the functionality of this module and noticed credential variable naming does not handle spaces in the username.

For example, on my SharePoint test VM some services use "Log On As" Network Service ("nt authority\\**network service**").

In the generated SP-Farm.DSC.ps1 script you can see the space in the username is also used in the variable name, which created invalid code:

```PowerShell
$Credsnetwork service = Get-Credential -UserName "nt authority\network service" -Message "Please provide credentials"
```

Also noted that a later credential variable is created with the same space issue, but also all in capitals this time:

```PowerShell
SPFarm SP01
        {
            FarmAccount = $CredsNETWORK SERVICE;
```

**The DSC configuration that is using the resource:**

N/A as only generating output at this stage.

**Version of the Operating System and PowerShell the DSC Target Node is running:**

Windows Server 2012 R2

```PowerShell
PS C:\Program Files\WindowsPowerShell\Scripts> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.14409.1012
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14409.1012
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Version of the DSC module you're using:**

Generated with:
1.9.1.0    ReverseDSC
1.9.0.0    SharePointDSC

**Comment by NikCharlebois** [comment]
@adamrushuk Will start investigating this....but first tell me, what do you get if you run 
(Get-SPFarm).DefaultServiceAccount.Name
On that farm?

**Comment by adamrushuk** [comment]
Thanks @NikCharlebois 

PS> (Get-SPFarm).DefaultServiceAccount.Name
NT AUTHORITY\NETWORK SERVICE

**Comment by NikCharlebois** [comment]
@adamrushuk Looks like the farm was originally created as a local account which is unfortunately not supported. I must admit, I am not even sure how that is even possible. Is this a multi server farm?

**Comment by adamrushuk** [comment]
I'm just using the evaluation from here: https://www.microsoft.com/en-gb/evalcenter/evaluate-sharepoint-server-2013

It's just a single server for testing.
I'll try re-installing and test again.

**Comment by NikCharlebois** [comment]
@Adamrushuk take a look at branch 1.9.1.0 which includes a fix for spaces in usernames. You will also need to grab the latest ReverseDSC bits from the Master branch

**Comment by adamrushuk** [comment]
Awesome, thanks @NikCharlebois.
I'll test this out soon and report back shortly.
