### ISSUE TITLE
A parameter cannot be found that matches parameter name 'WebAppUrl'

### ISSUE THREAD

**Issue by adamrushuk** [Microsoft/SharePointDSC.Reverse#40]
**Details of the scenario you try and problem that is occurring:**
I'm testing out SharePointDSC.Reverse against a vanilla SharePoint 2013 installation using evaluation media (https://www.microsoft.com/en-gb/evalcenter/evaluate-sharepoint-server-2013).

**Installation Steps:** 
1. Installed Software Prerequisites.
1. Installed SharePoint Server > Server Type: Complete.
1. SharePoint Products Configuration Wizard > Create a new Server Farm:
    1. Database server: `sql01`
    1. Database name: `SharePoint_Config`
    1. Database username: `LAB\sp_admin`
    1. Database password: `Passw0rds123`
    1. Passphrase for SP_Farm configuration (Server Joins): `Passw0rds123`
    1. Authentication Provider (Central Admin): `NTLM`

**Run Script**
```powershell
Set-Location -Path 'C:\Program Files\WindowsPowerShell\Scripts'
 .\SharePointDSC.Reverse.ps1
```

**Error During Export**
``` [ SP01 ] Scanning Alternate Url(s)...
Get-TargetResource : A parameter cannot be found that matches parameter name 'WebAppUrl'.
At C:\Program Files\WindowsPowerShell\Scripts\SharePointDSC.Reverse.ps1:3663 char:37
+       $results = Get-TargetResource @params
+                                     ~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Get-TargetResource], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Get-TargetResource

Cannot index into a null array.
At C:\Program Files\WindowsPowerShell\Modules\ReverseDSC\1.9.2.4\ReverseDSC.Core.psm1:173 char:16
+             if($null -eq $Params[$_])
+                ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : NullArray
```

**Issues noticed afterwards in SP-Farm.DSC.ps1**
1. The SharePointDSC ModuleVersion is `1.9.0.0` but `2.0.0.0` was installed at time of export.
1. SPFarm > ServerRole is blank: `ServerRole = ;`
1. The SPAlternateUrl section is blank.

**The DSC configuration that is using the resource:**
N/A as I'm just exporting right now; though I've attached `SP-Farm.DSC.ps1` in output.zip.

**Version of the Operating System and PowerShell the DSC Target Node is running:**
Server 2012R2

```powershell
[environment]::OSVersion.Version 

Major  Minor  Build  Revision
-----  -----  -----  --------
6      3      9600   0


$PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.14409.1012
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14409.1012
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Version of the DSC module you're using:**
```powershell
Get-Module -Name "*DSC*" -ListAvailable

    Directory: C:\Program Files\WindowsPowerShell\Modules

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Manifest   1.9.2.4    ReverseDSC                          {Get-DSCParamType, Get-DSCBlock, Get-DSCFakeParameters, Get-DSCDependsOnBlock...}
Manifest   2.0.0.0    SharePointDSC                       {Invoke-SPDSCCommand, Get-SPDSCInstalledProductVersion, Get-SPDSCContentService, Rename-SPDSCParamValue...}
Manifest   10.0.0.0   SqlServerDsc
Manifest   2.6.0.0    xDscDiagnostics                     {Trace-xDscOperation, Update-xDscEventLogStatus, Get-xDscOperation, Unprotect-xDscConfiguration...}
```

[output.zip](https://github.com/Microsoft/SharePointDSC.Reverse/files/1609790/output.zip)

**Comment by NikCharlebois** [comment]
Based on the output, it looks like you are using version 1.9.1.0 of the SharePointDSC.Reverse script along with SharePointDSC 2.0.0.0 which will cause the issues you are seeing. I recommend you get the latest version of all packages by running:
Install-Script SharePointDSC.Reverse -Force 

And then try again. Thanks

**Comment by adamrushuk** [comment]
Ah sorry Nik, I thought I was using the latest version already. 
Everything ran fine using the latest script.

Thanks for the swift response, and also for your awesome videos here: https://mva.microsoft.com/en-US/training-courses/sharepoint-automation-with-dsc-17843

**Comment by NikCharlebois** [comment]
Glad to hear it worked. Closing thenissue
